services:
  web:
    build: .
    ports:
      - "${PORT}:${PORT}"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${EXTERNAL_DATABASE_PORT}:${INTERNAL_DATABASE_PORT}"