services:
  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5434:${INTERNAL_DATABASE_PORT}"