version: '3.8'

services:
  web:
    extends:
      file: common-services.yml
      service: web
    depends_on:
      db:
        condition: service_healthy
  db:
    extends:
      file: common-services.yml
      service: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5